### ISSUE TITLE
As Cary, I want to be able to search by a training provider's industry

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#114]
As Cary,
I want to be able to search for training providers across the industry they provide training for,
So that I can help my customers generally see what's available

**GIVEN** I'm on the search page
**THEN** I can see a type-ahead search bar to search by type of training provider

[Type-Ahead Component](https://www.figma.com/file/A3EWVxJt2okRgxEakNyjtR/D4AD---Design-System?node-id=196%3A304)

**Comment by namanaman** [comment]
@cpenalosa How do we know a given provider or training's type?

**Comment by cpenalosa** [comment]
Closing issue pending Lesley's new categorization
