### ISSUE TITLE
Intercom Implementation and Onboarding

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#21]
- [ ] Implement FAQ pages
- [ ] Implement Intercom Widget with Macros to FAQ pages
- [x] settle on number of intercom seats
- [x] Create FAQ content for explorers
- [x] Create FAQ content for counselors
- [x] Create FAQ content for providers
- [x] Product Training and Onboarding

**Comment by cpenalosa** [comment]
Joe shared resources on Intercom implementation https://www.intercom.com/help/en/articles/167-install-intercom-on-your-website-and-chat-with-logged-out-visitors

**Comment by cpenalosa** [comment]
Ed shared resources on the Intercom Help Center: https://www.intercom.com/help/en/articles/56644-customize-your-help-center

**Comment by cpenalosa** [comment]
Interim plan is to implement chat widget on site, which will provide general workforce support and resources. This affects the following: 

- FAQs will be hosted on site and will be accessible through persona-based pages. This will help prevent Training Explorer specific articles from showing up in NJCN's Intercom widget.
- Macros will be used on Intercom to help people find the right content or get in touch with a support agent with a specific question
- FAQ Content editing and creation

**Comment by namanaman** [comment]
Closing similar to https://github.com/newjersey/d4ad/issues/14
