### ISSUE TITLE
Create event analytics dashboard via GA + Data Studio

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#248]

**Comment by namanaman** [comment]
What Google Analytics currently can track:
- [Needs to be confirmed] Which pages user goes to (what keyword do they search with, what training pages they visit, what occupation pages they visit, what FAQs they open)
- User characteristics (browser, device, location, time spent, where they came from)

What Google Analytics currently doesn't track:
- Switch language from English to Spanish
- Change Sort By selection
- Click Update Results
- Click Clear Filters
- Location filter, county filter, in demand filter, cost filter, class format filter, time to complete filter, provider services filters, languages filter (and Show More/Show Less), CIP filter, SOC filter
- Compare checkbox and further UI
- Click on stat block on training result page
- On training result page, click provider details links, associated occupations, Share this Training links
- On occupation page, related occupations links, search current openings link, related trainings links
