### ISSUE TITLE
As Cary, I need to be able to search for Workforce related codes to quickly find training opportunities

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#49]
As Cary,
I want to to search for a specific CIP or SOC code
so that I can quickly find training opportunities that lead to an in-demand occupation

--

**GIVEN** I am on the search page
**THEN** I can see a place to search for CIP or SOC codes

### Design
[Mobile](https://www.figma.com/file/A3EWVxJt2okRgxEakNyjtR/D4AD---Design-System?node-id=1088%3A610)
[Desktop](https://www.figma.com/file/A3EWVxJt2okRgxEakNyjtR/D4AD---Design-System?node-id=1088%3A532)
[Tablet](https://www.figma.com/file/A3EWVxJt2okRgxEakNyjtR/D4AD---Design-System?node-id=1088%3A532)

[CIP Code Component](https://www.figma.com/file/A3EWVxJt2okRgxEakNyjtR/D4AD---Design-System?node-id=204%3A2)
[SOC Code Component](https://www.figma.com/file/A3EWVxJt2okRgxEakNyjtR/D4AD---Design-System?node-id=204%3A3)

**Comment by namanaman** [comment]
@cpenalosa The Figma links above go to the landing page, I wasn't able to find the advanced search designs you were showing earlier, could you send the link to that? Also, is this CIP/SOC meant to be a filter or as part of the search query itself?

**Comment by cpenalosa** [comment]
@namanaman I updated the Figma links, it should be showing the correct frame now. The CIP/SOC are a filter you could apply and not intended to be part of the search query. Here's an example advanced search page of how it would be applied: https://njtrainingsystems.dol.state.nj.us/Search/ProgramSearchAdvanced.aspx
