### ISSUE TITLE
As Em, I want to know what additional support a given training offers

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#51]
As Em,
I need to know which training programs offer support services
So that I know which training opportunities can help me plan for life outside training

**GIVEN** I'm on the training detail page
**THEN** I can a see a place that describes what special services are available

[Desktop](https://www.figma.com/file/E93aghu0LH4kXQWReLfNNY/D4AD---Training-Explorer?node-id=1191%3A0)
[Tablet](https://www.figma.com/file/E93aghu0LH4kXQWReLfNNY/D4AD---Training-Explorer?node-id=667%3A654)
[Mobile](https://www.figma.com/file/E93aghu0LH4kXQWReLfNNY/D4AD---Training-Explorer?node-id=937%3A1578)

**Comment by namanaman** [comment]
@cpenalosa In terms of "Multiple Language Support", looking at the ETPL data, it's unclear to me what the "Other Languages" column is for. It has values `1` or `2`, do you know what they represent? The numbers don't seem to correlate with the "Languages" column in any way. Maybe this filter would just be seeing whether the "Languages" column is not empty?

<img width="227" alt="Screen Shot 2022-04-13 at 4 15 12 PM" src="https://user-images.githubusercontent.com/9057802/163263109-830f1f69-dcf9-476f-afca-11c5beb42909.png">

**Comment by cpenalosa** [comment]
@namanaman I just had a look at the data and it looks like there's two columns that "languages" refer to. One is the "otherlanguages" column and the other is "speakspanish" column. even with that said, it looks like there's some inconsistencies with the data assuming a value of 1 equals true and 2 equals false. 

For now, I think the best we can do with this filter is to show whether there's a value in the languages field. In a future ticket, we can also show the languages supported on the training detail page.

**Comment by namanaman** [comment]
@cpenalosa Okay thanks that makes sense. For the evening courses, I have the same question of what `1` and `2` refer to - which is true and which is false. Should I ask Lesley?

**Comment by cpenalosa** [comment]
@namanaman yeah let's ask Lesley about those values to double check. Looking at the data, about 2/3rds of programs do offer night courses if 1 equals true.
