### ISSUE TITLE
As Em, I want to see more human icons so that I can develop more of a visual connection to the Training Explorer

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#61]
User story to add staff imagery and illos.

**Comment by cpenalosa** [comment]
Change Training Provider icon on homepage: https://www.figma.com/file/E93aghu0LH4kXQWReLfNNY/D4AD---Training-Explorer?node-id=4374%3A9433

**Comment by namanaman** [comment]
New icon added
