### ISSUE TITLE
As Em, I want to know how a training opportunity contributes to my education

### ISSUE THREAD

**Issue by cpenalosa** [newjersey/d4ad#7]
As Em,
I want to know how a training opportunity contributes to my education,
So that I know if the opportunity it fits into my educational goals

**GIVEN** I'm on a training detail page
**THEN** I can see the associated degree, license, or certificate for that particular opportunity.

[Desktop](https://www.figma.com/file/E93aghu0LH4kXQWReLfNNY/D4AD-Training-Explorer?node-id=1191%3A0)
[Tablet](https://www.figma.com/file/E93aghu0LH4kXQWReLfNNY/D4AD-Training-Explorer?node-id=667%3A654)
[Mobile]()

**Comment by cpenalosa** [comment]
It looks like this is pulling prerequisites data instead of credential data, which is fine because that's useful information to have in the quick stats section. Is it possible to add the credential data into the quick stats section?

**Comment by skyfaerie** [comment]
Already there: https://d4ad-dev.appspot.com/training/21700. Doesn't seem to be too many.
